version: '3.7'

services:
  db:
    image: 'postgres:12-alpine'
    container_name: rockelivery-db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust    
    ports:
      - 5433:5432
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - ./docker/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql    

volumes:
  pgdata: